import React from "react";
import Navbar from "../../components/navbar";
import {Metadata} from "next";
import "../globals.css";

export const metadata: Metadata = {
    title: "Test",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode;
}) {
    return (
        <>
            <Navbar signUp='outlined' logIn='contained'/>
            {children}
        </>
    );
}
